apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: productservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: productservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
