apiVersion: v1
kind: Pod
metadata:
  name: productservice
  labels:
    app: productservice
spec:
  containers:
  - name: productservice
    image: markvincze/productservice:3
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
